language: csharp
solution: JoinMs2018.sln
mono:
  - 3.12.0
install:
  - nuget restore JoinMs2018.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory runner
script:
  - xbuild /p:Configuration=Release JoinMs2018.sln
  - mono ./runner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./JoinMs2018.Tests/bin/Release/JoinMs2018.Tests.dll
